<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>terere.ico</ApplicationIcon>
		<AssemblyName>terere</AssemblyName>
		<RootNamespace>terere</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="terere.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
	</ItemGroup>

</Project>
